# Generated by Django 3.2.9 on 2021-11-10 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='furniture',
            options={'verbose_name': 'Furniture', 'verbose_name_plural': 'Furniture'},
        ),
        migrations.AddField(
            model_name='furniture',
            name='picture',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='furniture',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
