# Generated by Django 3.2.9 on 2021-11-10 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20211110_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='furniture',
            name='condition',
            field=models.CharField(blank=True, choices=[('New', 'New'), ('Used Like New', 'Used Like New'), ('Good', 'Good'), ('Damaged', 'Damaged')], max_length=100),
        ),
    ]
