# Generated by Django 3.2.9 on 2021-11-10 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20211110_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furniture',
            name='location',
            field=models.CharField(choices=[('Lodi', 'Lodi')], default='Lodi', max_length=100, null=True),
        ),
    ]
