# Generated by Django 3.2.9 on 2021-11-11 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20211110_2244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='orders',
        ),
        migrations.AddField(
            model_name='furniture',
            name='source',
            field=models.CharField(blank=True, choices=[('Raymour & Flanigan', 'Raymour & Flanigan'), ('Facebook', 'Facebook')], max_length=100, null=True),
        ),
    ]
