# Generated by Django 3.2.9 on 2021-11-11 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20211111_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='furniture',
            name='list_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='furniture',
            name='comments',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='furniture',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
