# Generated by Django 3.2.9 on 2021-11-11 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_auto_20211111_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furniture',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='furniture',
            name='unit_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
