# Generated by Django 3.2.9 on 2021-11-17 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_auto_20211111_2202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='furniture',
            old_name='item',
            new_name='sub_category',
        ),
        migrations.AlterField(
            model_name='furniture',
            name='condition',
            field=models.CharField(blank=True, choices=[('New', 'New'), ('Used', 'Used'), ('Good', 'Good'), ('Damaged', 'Damaged')], max_length=100),
        ),
    ]
