# Generated by Django 3.2.9 on 2021-11-19 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_auto_20211117_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='furniture',
            name='listed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
