# Generated by Django 3.2.9 on 2021-11-19 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_furniture_listed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furniture',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='furniture',
            name='pcs',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='furniture',
            name='quantity',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
