# Generated by Django 3.2.9 on 2021-11-19 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_auto_20211119_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furniture',
            name='location',
            field=models.CharField(blank=True, choices=[('Lodi', 'Lodi')], default='Lodi', max_length=100, null=True),
        ),
    ]
